name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: r-devops-magistracy-project-2sem-2022036948
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

jobs:
  # Сборка и пуш образов в Docker Hub:
  build_and_push_to_docker_hub:
      name: Push Docker images to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          # Получение исходного кода из репозитория:
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          # Установка сборщика контейнеров Docker:
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          # Авторизация в Docker Hub:
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push Backend to Docker Hub
          # Одновременный билд и пуш образа в Docker Hub:
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: credo7/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}
        - name: Push Frontend to Docker Hub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: credo7/sausage-frontend:latest
        - name: Push Backend-report to Docker Hub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: credo7/sausage-backend-report:latest
  # Упаковываем helm-чарт и пушим его в Nexus
  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        
        - name: Install Helm
          uses: azure/setup-helm@v3
          with:
            version: '3.12.0'
        
        - name: Package Helm Chart
          run: |
            helm package ./sausage-store-chart
            
        - name: Login to Nexus Helm Registry
          run: |
            echo "${{ secrets.NEXUS_HELM_REPO_PASSWORD }}" | helm registry login ${{ env.NEXUS_HELM_REPO_HOST }} --username ${{ secrets.NEXUS_HELM_REPO_USER }} --password-stdin
          env:
            NEXUS_HELM_REPO_HOST: nexus.cloud-services-engineer.education-services.ru
            
        - name: Push Helm Chart to Nexus
          run: |
            helm push sausage-store-*.tgz oci://nexus.cloud-services-engineer.education-services.ru/repository/ah_vit-sausage-helm

  # Деплоим приложения в кластер Kubernetes с помощью helm-чарт
  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
        - name: Install Helm
          uses: azure/setup-helm@v3
          with:
            version: '3.12.0'
            
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
            
        - name: Create kubeconfig
          run: |
            echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
            chmod 600 $HOME/.kube/config
            
        - name: Login to Nexus Helm Registry
          run: |
            echo "${{ secrets.NEXUS_HELM_REPO_PASSWORD }}" | helm registry login nexus.cloud-services-engineer.education-services.ru --username ${{ secrets.NEXUS_HELM_REPO_USER }} --password-stdin
            
        - name: Deploy to Kubernetes
          run: |
            helm upgrade --install sausage-store oci://nexus.cloud-services-engineer.education-services.ru/repository/ah_vit-sausage-helm/sausage-store \
              --namespace $SAUSAGE_STORE_NAMESPACE \
              --wait --timeout=10m \
              --set global.imageRegistry=credo7