name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_REPO: nexus.cloud-services-engineer.education-services.ru
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: r-devops-magistracy-project-2sem-2022036948
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

jobs:
  # Сборка и пуш образов в Nexus:
  build_and_push_to_nexus:
      name: Push Docker images to Nexus
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          # Получение исходного кода из репозитория:
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          # Установка сборщика контейнеров Docker:
          uses: docker/setup-buildx-action@v2
        - name: Login to Nexus Docker Group Registry
          # Авторизация в Nexus Docker Group Registry:
          uses: docker/login-action@v2
          with:
            registry: ${{ env.NEXUS_REPO }}:18080
            username: ${{ secrets.NEXUS_HELM_REPO_USER }}
            password: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
        - name: Push Backend to Nexus
          # Одновременный билд и пуш образа в Nexus:
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ env.NEXUS_REPO }}:18080/sausage-backend:latest
            build-args: |
              VERSION=${{ github.sha }}
        - name: Push Frontend to Nexus
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ env.NEXUS_REPO }}:18080/sausage-frontend:latest
        - name: Push Backend-report to Nexus
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ env.NEXUS_REPO }}:18080/sausage-backend-report:latest
  # Упаковываем helm-чарт и пушим его в Nexus
  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_nexus

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        
        - name: Install Helm
          uses: azure/setup-helm@v3
          with:
            version: '3.12.0'
        
        - name: Package Helm Chart
          run: |
            helm package ./sausage-store-chart
            
        - name: Add Nexus Helm Repository
          run: |
            helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_HELM_REPO_USER --password $NEXUS_HELM_REPO_PASSWORD
            helm repo update
            
        - name: Push Helm Chart to Nexus
          run: |
            helm push sausage-store-*.tgz nexus

  # Деплоим приложения в кластер Kubernetes с помощью helm-чарт
  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
        - name: Install Helm
          uses: azure/setup-helm@v3
          with:
            version: '3.12.0'
            
        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.28.0'
            
        - name: Create kubeconfig
          run: |
            echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config
            chmod 600 $HOME/.kube/config
            
        - name: Add Nexus Helm Repository
          run: |
            helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_HELM_REPO_USER --password $NEXUS_HELM_REPO_PASSWORD
            helm repo update
            
        - name: Deploy to Kubernetes
          run: |
            helm upgrade --install sausage-store nexus/sausage-store \
              --namespace $SAUSAGE_STORE_NAMESPACE \
              --wait --timeout=10m \
              --set global.imageRegistry=${{ env.NEXUS_REPO }}